services:
  - type: web
    name: sharedocs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application
    postDeployCommand: python manage.py migrate --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - fromDotEnv: true
