services:
  - type: web
    name: sharedocs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - fromDotEnv: true

    postDeployCommand: |
      echo "Running migrations..."
      python manage.py migrate --noinput
      echo "Migrations done!"